package fr.geoffreyCoulaud.pinryReborn.api.usecases.exceptions

enum class ErrorCode {
    USERNAME_ALREADY_EXISTS,
    USER_DOES_NOT_EXIST,
    INVALID_PASSWORD,
    INVALID_LOGIN,
    INVALID_HTTP_AUTHORIZATION_SCHEME,
    PIN_DOES_NOT_EXIST,
    PIN_INSUFFICIENT_PERMISSIONS,
    PIN_NOT_SOFT_DELETED,
    PIN_ALREADY_SOFT_DELETED,
    SEARCH_EMPTY_QUERY,
}
